#!/bin/bash
# Install or remove the hol-lab systemd service. Does not modify setup.sh or cleanup.sh.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_NAME="hol-lab.service"
STARTER="/usr/local/bin/hol-lab-start.sh"
UNIT="/etc/systemd/system/${SERVICE_NAME}"

usage() {
  echo "Usage: sudo $0 [install|uninstall] [--no-start]"
  echo "  install    - install systemd service and starter (default)"
  echo "  uninstall  - disable and remove the service"
  echo "  --no-start - with install: enable only, do not start immediately"
}

if [[ "${EUID:-0}" -ne 0 ]]; then
  echo "Error: run as root, e.g. sudo $0"
  exit 1
fi

DO_START=1
ACTION="install"
for arg in "$@"; do
  case "$arg" in
    install) ACTION="install" ;;
    uninstall) ACTION="uninstall" ;;
    --no-start) DO_START=0 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $arg"; usage; exit 1 ;;
  esac
done

if [[ "$ACTION" == "uninstall" ]]; then
  systemctl stop "$SERVICE_NAME" 2>/dev/null || true
  systemctl disable "$SERVICE_NAME" 2>/dev/null || true
  rm -f "$STARTER"
  rm -f "$UNIT"
  systemctl daemon-reload
  echo "Removed $SERVICE_NAME and $STARTER"
  exit 0
fi

# --- install ---
cat > "$STARTER" <<'INSTALL_EOF'
#!/bin/bash
# Generated by hol install.sh — runs cleanup then setup on boot (or when started).
set -euo pipefail
HOL_DIR="@HOL_DIR@"
cd "$HOL_DIR" || exit 1

for _ in $(seq 1 30); do
  docker info &>/dev/null && break
  sleep 2
done
if ! docker info &>/dev/null; then
  echo "hol-lab: Docker is not available" >&2
  exit 1
fi

# If a previous lab deployment exists, tear it down before setup.
if docker ps -a --format '{{.Names}}' | grep -qE '^(frr[0-9]+|dhcpd[0-9]+|radiusd[0-9]+|nginx-hol)$'; then
  bash "$HOL_DIR/cleanup.sh"
fi
bash "$HOL_DIR/setup.sh"
INSTALL_EOF
# Escape path for sed replacement (handles / & \ etc.)
HOL_SED=$(printf '%s\n' "$SCRIPT_DIR" | sed 's/[\/&|]/\\&/g')
sed -i "s#@HOL_DIR@#$HOL_SED#g" "$STARTER"
chmod 755 "$STARTER"

cat > "$UNIT" <<EOF
[Unit]
Description=HOL FRR lab (cleanup then setup)
After=docker.service network-online.target
Wants=network-online.target docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=$STARTER

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
if [[ "$DO_START" -eq 1 ]]; then
  systemctl start "$SERVICE_NAME"
  echo "Enabled and started $SERVICE_NAME"
else
  echo "Enabled $SERVICE_NAME (not started; use: sudo systemctl start $SERVICE_NAME)"
fi
