services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "13"
      ARGUMENTS: "-device usb-host,vendorid=0x0bda,productid=0x8153"
    devices:
      - /dev/bus/usb
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./macos:/storage
    restart: always
    stop_grace_period: 2m
