# Check https://github.com/qemus/qemu for details
services:
  qemu:
    image: qemux/qemu
    container_name: ubuntu
    environment:
      BOOT: "ubuntu"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DHCP: "Y" # If using Static IP remove this line
      #ARGUMENTS: "-device usb-host,vendorid=0x1234,productid=0x1234" # Passing USB Wireless NIC. Remove this line if no WiF. Use lsusb to get vendorid and productid
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net # Only needed if DHCP="Y". For static remove this line
    device_cgroup_rules: # Only needed if DHCP="Y". For static remove this line
      - 'c *:* rwm' # Only needed if DHCP="Y". For static remove this line
    cap_add:
      - NET_ADMIN
    ports:
      - 8007:8006 #When running multiple containers use a diffrent port (8007 in this case) for every container.
    volumes:
      - ./ubuntu:/storage
    restart: always
    stop_grace_period: 2m
    networks:
      pc_net: # This name needs to match the macvlan docker network name

networks:
  pc_net: # This name needs to match the macvlan docker network name
    external: true